function result = finiteautomaton(automatonname, string, formatoption, randomseed)
% result = finiteautomata(automatonname, string, formatoption, randomseed)
%
% Computation for a given finite automaton and string.
%   `result` is either
%      1 : accepted string
%      0 : rejected string in non final state, or
%     -1 : rejected string with blocked computation (only NDFA).
%
% The automaton can be either DFA or NFA, and it is defined
% in a JSON file, like this:
%
%   {
%     "K" : ["q0", "q1", "q2"],
%     "A" : ["a", "b"],
%     "s" : "q0",
%     "F" : ["q2"],
%     "t" : [["q0", "a", "q1"],
%            ["q1", "a", "q1"],
%            ["q1", "b", "q2"],
%            ["q2", "b", "q2"]]
%   }
%
%   (a transition consuming the empty string: ["q1", "", "q2"])
%
%  formatoption is either undefined or "LaTeX" for LaTeX-formatted output.
%
%
% For example:
%
%    >> finiteautomaton("aa*bb*", "ab")
%
%    M = ( {q0, q1, q2}, {a, b}, {(q0, a, q1), (q1, a, q1), (q1, b, q2), (q2, b, q2)}, q0, {q0, q1, q2} )
%
%    w = ab
%
%    (q0, ab) ⊢ (q1, b) ⊢ (q2, ε)
%
%    w ∈ 𝓛(M)
%
%    >> finiteautomaton("aa*bb*", "ab", "LaTeX")
% ===============================================================
%
%   fjv, 25/10/2018   GNU GPL v3.0
%   fjv, 02/01/2022   loads from automata database
%   fjv, 19/02/2022   printautomaton fixed
%   fjv, 23/02/2022   printautomaton fixed
%
% ===============================================================

  languagesymbol = "𝓛";
  openbracket  = "{";
  closebracket = "}";

  ## check if called from LuaTex and adapt special characters
  files = dbstack;
  caller = files(end).file;
  if strfind(caller, "runexample.m")
    languagesymbol  = "$\\pazocal{L}$";
    openbracket  = strcat("\\", openbracket);
    closebracket = strcat("\\", closebracket);
  end

  ## random seed
  if !exist('randomseed','var')
    randomseed = rand(1);
  end

  ## database of finite automata
  automatadatabasename = 'finiteautomata';

  addpath("../util/");
  
  emptystring      = "ε";
  transitionsymbol = "⊢";

  if exist('formatoption', 'var') && strcmp(formatoption, "LaTeX")
    formatoptionLaTeX = true;
  else
    formatoptionLaTeX = false;
  end
  
  ## load automaton definition from JSON file
  # check if the automaton is given as an structure
  #   as generated by randomautomaton
  if isstruct(automatonname)
    automaton = automatonname;
  else
    automaton = loadrepresentation(automatadatabasename, automatonname);
  end

  printautomaton(automaton, string, formatoptionLaTeX);

  rand('seed', randomseed);


  ## define initial configuration
  initialconfiguration = {automaton.s, string};

  currentconfiguration = initialconfiguration;  
  if formatoptionLaTeX
    printf("$");
  end
  printconfiguration(currentconfiguration, string, formatoptionLaTeX);
  do
    ## compute while a transition can be done
    [nextconfiguration, unabletotransit] = transit(automaton.t, currentconfiguration);
    if !unabletotransit
      if formatoptionLaTeX
        printf(" \\vdash ");
      else
        printf(" %s ", transitionsymbol);
      end
      printconfiguration(nextconfiguration, emptystring, formatoptionLaTeX);
      currentconfiguration = nextconfiguration;
    end
  until unabletotransit;
  if formatoptionLaTeX
    printf("$");
  end
  printf("\n");
  
  if isempty(currentconfiguration{2})
    ## input string is empty
    terminalstate = currentconfiguration{1};
    if ismember(terminalstate, automaton.F)
      ## terminal state is a final state
      printf("\nw ∈ %s(M)\n", languagesymbol);
      result = 1;
    else
      ## terminal state is not a final state
      if isDFA(automaton)
        printf("\nw ∉ %s(M)\n", languagesymbol);
      else
        printf("w not accepted by M.\n");
      end
      result = 0;
    end
  else
    ## input string is not empty
    printf("Blocked computation, w not accepted by M.\n");
    result = -1;
  end

  function result = isDFA(automaton)

    statesymbol = zeros(numel(automaton.K), numel(automaton.A));
    for transition = automaton.t
      statesymbol(find(strcmp(transition{1}(1), automaton.K)), ...
                  find(strcmp(transition{1}(2), automaton.A))) = 1;  
    end
    result = sum(sum(statesymbol)) == numel(automaton.K) * numel(automaton.A);
  end

  function [nextconfiguration, unabletotransit] = transit(relation, currentconfiguration)
  ## transit from current to next configuration, if possible

    state  = currentconfiguration{1};
    string = currentconfiguration{2};

    ## check what are valid transitions from current state and string
    nextconfiguration = {};
    validtransitions = 0;
    for transitionid = 1 : numel(relation)
      ## get transition, e.g. (q0, abc, q1)
      transition    = relation{transitionid};
      currentstate  = transition{1};
      consumed      = transition{2};
      nextstate     = transition{3};

      if strcmp(state, currentstate)
        ## check if consumed string is a prefix of string
        if !isempty(consumed)
          [first, last] = regexp(string, consumed);
          if !isempty(first) && first(1) == 1
            ## it is a prefix
            if last(1) == numel(string)
              ## the automaton consumes all the remaining symbols
              nextstring = "";
            else
              nextstring = substr(string, last(1) + 1);
            end
            nextconfiguration{++validtransitions} = {nextstate, nextstring};
          end
        else
          ## the string to be consumed is an empty string
          if rand > 0.5
            ## assign probability of transition to avoid infinite loops
            nextconfiguration{++validtransitions} = {nextstate, string};
          end
        end
      end
    end

    unabletotransit = (numel(nextconfiguration) == 0);
    if !unabletotransit
      ## choose one transition among the valid ones
      nextconfiguration = nextconfiguration{ceil(rand * numel(nextconfiguration))};
    end
  end


  function printconfiguration(configuration, string, formatoptionLaTeX)
  ## print formatted configuration, e.g. (q0, b) or (q2, ε)

    string = configuration{2};
    if isempty(string)
      ## represent with empty string symbol
      if formatoptionLaTeX
        string = "\\varepsilon";
      else
        string = emptystring;
      end
    end

    printf("(%s, %s)", formatstate(configuration{1}, formatoptionLaTeX), string);
  end


  function state = formatstate(state, formatoptionLaTeX)
  
    if formatoptionLaTeX
      state = sprintf("%s_%s", state(1),state(2:end));
    end  
  end
  
  
  function printautomaton(automaton, string, formatoptionLaTeX)
  ## print formatted automaton, e.g.
  ## M = ( {q0, q1, q2}, {a, b}, {(q0, a, q1), (q1, a, q1), (q1, b, q2), (q2, b, q2)}, q0, {q0, q1, q2} )

    ## format states
    K = "";
    for element = 1 : numel(automaton.K)
      if element > 1
        K = cstrcat(K, ", ");
      end
      K = cstrcat(K, formatstate(automaton.K{element}, formatoptionLaTeX));
    end

    ## format alphabet
    A = "";
    for element = 1 : numel(automaton.A)
      if element > 1
        A = cstrcat(A, ", ");
      end
      A = cstrcat(A, automaton.A{element});
    end
    
    s = automaton.s;

    ## format final states
    F = "";
    for element = 1 : numel(automaton.F)
      if element > 1
        F = cstrcat(F, ", ");
      end
      F = cstrcat(F, formatstate(automaton.F{element}, formatoptionLaTeX));
    end

    ## format transition relation  
    t = "";
    for transitionid = 1 : numel(automaton.t)
      if transitionid > 1
        t = cstrcat(t, ", ");
      end
      transition = automaton.t{transitionid};
      consumed = transition{2};
      if isempty(consumed)
        consumed = emptystring;
      end
      t = cstrcat(t, "(", formatstate(transition{1}, formatoptionLaTeX), ", ", consumed, ", ", formatstate(transition{3}, formatoptionLaTeX), ")");
    end

    if formatoptionLaTeX
      printf("\n$M = (\\{%s\\}, \\{%s\\}, \\{%s\\}, %s, \\{%s\\})$\n", K, A, t, formatstate(s, formatoptionLaTeX), F);
      printf("\n$w = %s$\n\n", string);
    else
      printf("\nM = (%s%s%s, %s%s%s, %s%s%s, %s, %s%s%s)\n", openbracket, K, closebracket, openbracket, A, closebracket, openbracket, t, closebracket, s, openbracket, F, closebracket);
      printf("\nw = %s\n\n", string);
    end
  
  end
  
end

