function formatautomaton(automaton, outputfilename)
    # formatautomaton(automaton, outputfilename)
    # https://graphviz.org/documentation
    #
    # optional: outputfilename
    #
    # Generates a Dot/Graphviz representation of the automaton.
    #
    # examples
    #   formatautomaton(randomautomaton({'a', 'b', 'c'}, 4, 'NPDA'))
    #   fa = randomautomaton({'0', '1'}, 5, 'NDA'); formatautomaton(fa, 'DOT_file');
    #   formatautomaton('0^n1^2n')
    #   formatautomaton('a*bb*aa*')
    #
    #=============================================================
    #
    #   fjv, 08/02/2022   GNU GPL v3.0
    #
    #=============================================================

    emptystring_orig = "ε";
    emptystring = emptystring_orig;
    transitionsymbol = "⊢";

    ## check if called from LuaTex and adapt special characters
    files = dbstack;
    caller = files(end).file;

    if strfind(caller, "runexample.m")
        emptystring = "$\\varepsilon$";
        transitionsymbol = "$\\vdash$";
    end

    addpath("../util/");

    emptystring = "*";
    #  emptystring      = "ε";
    transitionsymbol = "⊢";
    font = "times-italic";
    finiteautomata = "finiteautomata";
    pushdownautomata = "pushdownautomata";

    # check if the automaton is given as an structure
    #   as generated by randomautomaton
    if !isstruct(automaton) && ischar(automaton)
        # automaton stored in a JSON file, go fetch it
        automatondescription = automaton;

        # check if in finite automaton database
        automaton = loadrepresentation(finiteautomata, automatondescription);

        if ischar(automaton)
            # check if in pushdown automaton database
            automaton = loadrepresentation(pushdownautomata, automatondescription);

            if ischar(automaton)
                # load from a specific file
                if !exist(automaton, 'file')
                    error(sprintf('file "%s" does not exist\n', automatondescription));
                else
                    automaton = loadjson(automatondescription);
                end

            end

        end

    end

    if exist('outputfilename', 'var')
        fileid = fopen(outputfilename, 'wt');
    else
        fileid = stderr;
    end

    # print Dot/Graphviz representation
    fprintf(fileid, 'digraph finite_state_machine {\n');
    fprintf(fileid, '  rankdir=LR;\n');
    fprintf(fileid, '  size="%d"\n', numel(automaton.K));
    fprintf(fileid, '  node [fontname="%s"];\n', font);
    fprintf(fileid, '  edge [fontname="%s"];\n', font);
    fprintf(fileid, '  node [shape = point]; qi\n', font);

    if !isempty(automaton.F)
        fprintf(fileid, '  node [shape = doublecircle]; %s', automaton.F{1});

        for stateid = 2:numel(automaton.F)
            fprintf(fileid, ',%s', automaton.F{stateid});
        end

        fprintf(fileid, ';\n');
    end

    fprintf(fileid, '  node [shape = circle];\n');
    fprintf(fileid, '  qi -> %s;\n', automaton.s);

    for transitionid = 1:numel(automaton.t)
        transition = automaton.t{transitionid};

        if numel(transition) == 3
            # it is a FA
            sourcestate = transition{1};
            inputstring = transition{2};
            targetstate = transition{3};

            if strcmp(inputstring, emptystring_orig)
                inputstring = emptystring;
            end

        else
            # it is a NPA
            sourcestate = transition{1}{1};
            inputstring = transition{1}{3};
            stackstring = transition{2}{2};

            if strcmp(inputsymbol, emptystring_orig)
                inputsymbol = emptystring;
            end

            if strcmp(stackstring, emptystring_orig)
                stackstring = emptystring;
            end

            string = sprintf("%s/%s/%s", transition{1}{2}, inputstring, stackstring);
            targetstate = transition{2}{1};
        end

        fprintf(fileid, '  %s -> %s [ label = "%s" ];\n', sourcestate, targetstate, inputstring);
    end

    fprintf(fileid, '}\n');

    if exist('outputfilename', 'var')
        fclose(outputfilename);
    end

end
